apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openshift-gitops-argocd-application-controller
    app.kubernetes.io/part-of: openshift-gitops
    app.kubernetes.io/component: openshift-gitops-argocd-application-controller
  name: openshift-gitops-argocd-application-controller
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
