apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ilab-ui-stack-qa
spec:
  project: default
  source:
    repoURL: https://github.com/instructlab/ui.git
    path: deploy/k8s/overlays/openshift/qa
    targetRevision: main
  destination:
    namespace: instructlab
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true

