apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: cluster-management
  source:
    path: sealed-secrets/overlays/rosa
    repoURL: https://github.com/redhat-et/rosa-apps.git
    targetRevision: main
