FROM golang:1.22-alpine as builder

WORKDIR /pathservice

COPY ./pathservice ./

# Build the Go app
RUN go build -o /go/bin/pathservice

# Start a new stage from scratch
FROM alpine:3.14

# Copy the binary from the previous stage
COPY --from=builder /go/bin/pathservice /pathservice

# Expose the port 4000 to the outside world
EXPOSE 4000

# Command to run the executable
CMD ["/pathservice"]
