FROM registry.access.redhat.com/ubi9-minimal:9.5-1731593028

RUN microdnf install -y jq python3 python3-pip

COPY sidecar-script.py requirements.txt /home

RUN python3 -m pip install -r /home/requirements.txt

ENTRYPOINT ["python3", "/home/sidecar-script.py"]
